// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjNKXkr-RUJzfkoaKmriDwf0-HfHNGM0',
    appId: '1:47999850982:web:2055fb8e43a32636119e27',
    messagingSenderId: '47999850982',
    projectId: 'restaurantapp-4c6f7',
    authDomain: 'restaurantapp-4c6f7.firebaseapp.com',
    storageBucket: 'restaurantapp-4c6f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmhJJ9as4kLAwIzuvrunhYpikl8BXBSU',
    appId: '1:47999850982:android:b980611cd6c060a4119e27',
    messagingSenderId: '47999850982',
    projectId: 'restaurantapp-4c6f7',
    storageBucket: 'restaurantapp-4c6f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7uj0SHYo6qBjB_aU_79zMNFdaDs5Wgs',
    appId: '1:47999850982:ios:b731b58780519672119e27',
    messagingSenderId: '47999850982',
    projectId: 'restaurantapp-4c6f7',
    storageBucket: 'restaurantapp-4c6f7.appspot.com',
    iosClientId: '47999850982-aqda1gjfkl8vjmisdtuiqd2dcg721qb0.apps.googleusercontent.com',
    iosBundleId: 'com.combosko.genba.restaurantApp',
  );
}
